apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "whereabouts.fullname" . }}-config
  {{- include "whereabouts.namespace" . | nindent 2 }}
  labels:
    {{- include "whereabouts.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/description: |
      Configmap containing user customizable cronjob schedule
data:
  cron-expression: {{ .Values.reconcilerCronExpression }}
