# Copyright 2020 K8s Network Plumbing Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
{{- if or ( gt .Capabilities.KubeVersion.Major "1" ) ( ge .Capabilities.KubeVersion.Minor "16" ) }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-ds
  namespace: kube-system
  labels:
    app: multus
    {{- include "multus.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      app: multus
      {{- include "multus.labels" . | indent 6 }}
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: multus
        {{- include "multus.labels" . | indent 8 }}
    spec:
      priorityClassName: system-node-critical
      hostNetwork: true
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector: {{ . }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
      - name: multus
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: KUBERNETES_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        command: ["/thin_entrypoint"]
        args:
          {{- with .Values.args.cniBinDir }}
          - --cni-bin-dir={{ . }}
          {{- end }}
          {{- with .Values.args.cniConfDir }}
          - --cni-conf-dir={{ . }}
          {{- end }}
          {{- with .Values.args.cniVersion }}
          - --cni-version={{ . }}
          {{- end }}
          {{- with .Values.args.multusConfFile }}
          - --multus-conf-file={{ . }}
          {{- end }}
          {{- with .Values.args.multusBinFile }}
          - --multus-bin-file={{ . }}
          {{- end }}
          {{- with .Values.args.multusCNIConfDir }}
          - --multus-cni-conf-dir={{ . }}
          {{- end }}
          {{- with .Values.args.skipMultusBinaryCopy }}
          - --skip-multus-binary-copy={{ . }}
          {{- end }}
          {{- with .Values.args.multusKubeConfigFileHost }}
          - --multus-kubeconfig-file-host={{ . }}
          {{- end }}
          {{- with .Values.args.multusMasterCNIFileName }}
          - --multus-master-cni-file-name={{ . }}
          {{- end }}
          {{- with .Values.args.namespaceIsolation }}
          - --namespace-isolation={{ . }}
          {{- end }}
          {{- with .Values.args.globalNamespaces }}
          - --global-namespaces={{ . }}
          {{- end }}
          {{- with .Values.args.multusAutoconfigDir }}
          - --multus-autoconfig-dir={{ . }}
          {{- end }}
          {{- with .Values.args.multusLogToStderr }}
          - --multus-log-to-stderr={{ . }}
          {{- end }}
          {{- with .Values.args.multusLogLevel }}
          - --multus-log-level={{ . }}
          {{- end }}
          {{- with .Values.args.multusLogFile }}
          - --multus-log-file={{ . }}
          {{- end }}
          {{- with .Values.args.overrideNetworkName }}
          - --override-network-name={{ . }}
          {{- end }}
          {{- with .Values.args.cleanupConfigOnExit }}
          - --cleanup-config-on-exit={{ . }}
          {{- end }}
          {{- with .Values.args.skipConfigWatch }}
          - --skip-config-watch={{ . }}
          {{- end }}
          {{- with .Values.args.renameConfFile }}
          - --rename-conf-file={{ . }}
          {{- end }}
          {{- with .Values.args.readinessIndicatorFile }}
          - --readiness-indicator-file={{ . }}
          {{- end }}
          {{- with .Values.args.additionalBinDir }}
          - --additional-bin-dir={{ . }}
          {{- end }}
          {{- with .Values.args.skipTLSVerify }}
          - --skip-tls-verify={{ . }}
          {{- end }}
          {{- with .Values.forceCNIVersion }}
          - --force-cni-version={{ . }}
          {{- end }}
        {{- with .Values.resources}}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.securityContext}}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        volumeMounts:
        - name: cni
          mountPath: /host/etc/cni/net.d
        - name: cnibin
          mountPath: /host/opt/cni/bin
      initContainers:
      - name: install-multus-binary
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        command: [ "/install_multus" ]
        args:
          - "--type"
          - "thin"
        resources:
          requests:
            cpu: "10m"
            memory: "15Mi"
        securityContext:
          privileged: true
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
          - name: cnibin
            mountPath: /host/opt/cni/bin
            mountPropagation: Bidirectional
      volumes:
        - name: cni
          hostPath:
            path: /etc/cni/net.d
        - name: cnibin
          hostPath:
            path: /opt/cni/bin
{{- end }}

